# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: 'InfoMapper (Developer)'
nav:
- Home: 'index.md'
- Introduction: 'introduction/introduction.md'
- New Developer: 'dev-new/dev-new.md'
- Software Design: 'software-design/software-design.md'
- UI Design: 'ui-design/ui-design.md'
- Development Tasks:
  - Overview: dev-tasks/overview.md
  - Version Control: dev-tasks/version-control.md
  - Editing Code: dev-tasks/editing.md
  - Adding a New Module: dev-tasks/add-module.md
  - Documenting: dev-tasks/documenting.md
  - Running & Usage: dev-tasks/running.md
  - Testing: dev-tasks/testing.md
  - Deploying: dev-tasks/deploying.md
  - Creating Installer: dev-tasks/creating-installer.md
- Development Environment:
  - Overview: 'dev-env/overview.md'
  - Development Folders: 'dev-env/folders.md'
  - Node: 'dev-env/node.md'
  - Angular: 'dev-env/angular.md'
  - QGIS: 'dev-env/qgis.md'
  - Visual Studio Code: 'dev-env/vs-code.md'
  - MkDocs: 'dev-env/mkdocs.md'
  - Git: 'dev-env/git.md'
  - Cygwin: 'dev-env/cygwin.md'
  - Running the InfoMapper: 'dev-env/running.md'
- Testing: 'testing/testing.md'
- Troubleshooting: 'troubleshooting/troubleshooting.md'
- Resources: 'resources/resources.md'
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  'Copyright Open Water Foundation'
# ------------------------------------------------
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
# google_analytics:
#  - 'UA-135465513-1'
#  - auto
# ------------------------------------------------
# Favicon is supposed to automatically be found:
# - in docs/img/favicon.ico
# - is a copy of docs/images/OWF-Logo-Favicon-32x32.ico
# - instead, with Material them, have a different approach (see "theme" below)
# ------------------------------------------------
# Don't specify the repository because doing show shows irritating edit
# icons on every page - instead, edit the documentation in the developer environment.
#repo_url:  https://github.com/OpenWaterFoundation/owf-app-infomapper-ng
# ------------------------------------------------
site_author:  'Open Water Foundation'
site_description:  'Open Water Foundation Learn InfoMapper (for Developers)'
# ------------------------------------------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  favicon:  'images/favicon.ico'
# ------------------------------------------------
# The following controls how URLs are created
# - As of MkDocs 1.0 the default is true meaning URLs to a page ABC is ABC/ rather than something/ABC.html.
# - see:  https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
# use_directory_urls: true
# ------------------------------------------------
